# More information about the configuration file can be found here:
# https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/serverless-sam-cli-config.html
version = 0.1

[default]
[default.global.parameters]
stack_name = "index-sync"

[default.build.parameters]
cached = true
parallel = true

[default.validate.parameters]
lint = true

[default.deploy.parameters]
capabilities = "CAPABILITY_IAM"
confirm_changeset = true
resolve_s3 = true
s3_prefix = "index-sync"
region = "eu-central-1"
disable_rollback = true
image_repositories = []

[default.package.parameters]
resolve_s3 = true

[default.sync.parameters]
watch = true

[default.local_start_api.parameters]
warm_containers = "EAGER"
parameter_overrides = "TargetEnv=\"testnet\" LiteConnectionURL=\"https://ton.org/global.config.json\" TonStakersAddress=\"EQD2_4d91M4TVbEBVyBF8J1UwpMJc361LKVCz6bBlffMW05o\" KeyPairSecretName=\"fiva_keypair\""

[default.local_start_lambda.parameters]
warm_containers = "EAGER"

[testnet.deploy.parameters]
region = "ue-central-1"
parameter_overrides = "TargetEnv=\"testnet\" LiteConnectionURL=\"https://ton.org/global.config.json\" TonStakersAddress=\"EQD2_4d91M4TVbEBVyBF8J1UwpMJc361LKVCz6bBlffMW05o\" KeyPairSecretName=\"fiva_keypair\""

[mainnet.deploy.parameters]
region = "ue-central-1"
parameter_overrides = "TargetEnv=\"testnet\" LiteConnectionURL=\"https://ton.org/global.config.json\" TonStakersAddress=\"EQD2_4d91M4TVbEBVyBF8J1UwpMJc361LKVCz6bBlffMW05o\" KeyPairSecretName=\"fiva_keypair\""