AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  index-sync

  SAM for index-sync

Parameters:
  TargetEnv:
    Type: String
    Description: Target environment
  LiteConnectionURL:
    Type: String
    Description: URL to TON lite client
  TonStakersAddress:
    Type: String
    Description: TON Stakers minter address
  KeyPairSecretName:
    Type: String
    Description: Name of secret variable stored into Secret Manager
Globals:
  Function:
    Timeout: 60
    MemorySize: 128
    LoggingConfig:
      LogFormat: JSON
Resources:
  IndexSyncFunction:
    Type: AWS::Serverless::Function
    Metadata:
      BuildMethod: go1.x
    Properties:
      CodeUri: service/
      Handler: bootstrap
      Runtime: provided.al2023
      Architectures:
        - x86_64
      Events:
        CatchAll:
          Type: Api
          Properties:
            Path: /index
            Method: GET
      Environment:
        Variables:
          TARGET_ENV: !Ref TargetEnv
          LITE_CONNECTION_URL: !Ref LiteConnectionURL
          TON_STAKERS_ADDRESS: !Ref TonStakersAddress
          KEY_PAIR_SECRET_NAME: !Ref KeyPairSecretName

Outputs:
  API:
    Description: API Gateway endpoint URL for target environment
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/${TargetEnv}/index/"
  Function:
    Description: Index sync Lambda Function ARN
    Value: !GetAtt IndexSyncFunction.Arn
  FunctionIamRole:
    Description: Implicit IAM Role created for Index Sync function
    Value: !GetAtt IndexSyncFunctionRole.Arn
